// <auto-generated />
namespace LibraryApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LessonsIki : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LessonsIki));
        
        string IMigrationMetadata.Id
        {
            get { return "202201190952532_LessonsIki"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
