// <auto-generated />
namespace LibraryApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Duzenleme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Duzenleme));
        
        string IMigrationMetadata.Id
        {
            get { return "202201211646093_Duzenleme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
